language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements_python2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install -r requirements_python3.3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 3.3 ]]; then pip install -r requirements_python3.4.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then pip install -r requirements_python2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy3* ]]; then pip install -r requirements_pypy3.txt; fi
  - pip install pytest-cov coveralls
# command to run tests
script: py.test --cov=graphcore
notifications:
  email:
    - zdwiel@gmail.com
after_success:
  - coveralls
